# Javascript Node CircleCI 2.0 configuration file
version: 2
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: circleci/node:13.14.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build the application
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - package.json
            - node_modules
            - src
            - build
  deploy-test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          #Get all pre-requisites
          command: |
            apk add --no-cache \
            py-pip=9.0.0-r1
            pip install --upgrade pip \
            awscli==1.14.37
            aws s3 sync . s3://zohaibcircleci
  deploy-production:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          #Get all pre-requisites
          command: |
            apk add --no-cache \
            py-pip=9.0.0-r1
            pip install --upgrade pip \
            awscli==1.14.37
            aws s3 sync .  s3://zohaibcircleci
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy-test:
          context: AWS
          requires:
            - build
          filters:
            branches:
              only:
                - test
      - deploy-production:
          context: AWS
          requires:
            - build
          filters:
            branches:
              only:
                - master